name: Verify CI

on:
    pull_request:
        branches:
          - 'master'
          - 'dev'

jobs:
  call_workflow:
    uses: PrintScript8/ingsis-library/.github/workflows/on-pull-request-printscript.yml@main