name: Verify CI

on:
    pull_request:
        branches:
          - 'master'
          - 'dev'

jobs:
  workflow_call:
    uses: PrintScript8/ingsis-library/.github/workflows/on-pull-request.yml@main
